name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Cargo fmt
      run: cargo fmt -- --check
    - name: Security
      run: cargo audit
    - name: Code coverage
      run: cargo tarpaulin --ignore-tests
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
